# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ba117d3651c2d53fc3779faa6424c76d727970f644f17648d663bbfdbf1e93ee0c3c8ac5004ad0a58705736f68a6bfc54c6fa58f9d559412bbacf1f400d00a

test:
  secret_key_base: 4c8a3671eccfa41005b73e68e2a80cd0495715abf0a17b9f91ca7da929e0e49553cd77e8d5523de575e5dfd92930fa2711b88ed44fd0af708ae927950f70f6cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
